language: ruby
cache: bundler
rvm:
- 2.5.1
before_script:
- bundle exec rake db:setup
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: Na+nxDCSOFaDmzFNZ8ObfOegKvRsPSMkRRqAiwtr1aGGHRkcJK+ySpEz66lX6RItGDvYZgL5Su6a0CuxGoKC5I9RJG5LKITwTO3Z8IWRWXojwupoorspcEl+4rPUM1h49KG3v0UqisH52dgZ4E74RTXIdPC/5BiJxUeHAZhv6TL90xoO67uTcPIBjGrLKDoFwgMmLiiDXX2Tl1sq7D+MzJYPkiMLgvP4wolUSczMW4444brBIGYq63F9szAI6jBTfqIVabrGrwBmYgQ9c6qFuZeR7KW41AI1oH7WIuBO/H4f5UdafaSgEFirOLWXVczLdhWEK9HhpbMLvmAf3INThFF6Q8473E+arrbFMliZO8aYkj9Rs2d8tu2kE/ASOdLMgGjVpmkT02uhlmEqnMItU45yfjuci0tswmv8tf4zA8YYTOAOz4n7nrIbfjM9DguuN6NxATHVSvSDa6wANY8jPEhbqS6xnCq443X7r4TDkLxTh+QXSpTYZjg5+sZ2JH/Iorre+QjNmmTvg0oJ7QEHYTccjfCHBJ/V1TPZpnlc8Xah68avdbF2PkPS51rCa/fTHq4AFz0Nr2E8kCurRxozabJXBx2IX7KrnqZ0W8LttGX7GDm2TufkielYq3WwDtb14CVIkMUSyPuQjXDnCe87w+fAqXwGwPxhOfelL98pq5c=
  app: imstagramm
