language: ruby
cache: bundler
rvm:
- 2.5.1
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: OkAmL24/lbV9im299qOOZUzwez+SQ2Zcn7uuLcb5xLd7Lt6tA0qJLgzq7CtHjZgcb+/hNsZsLB6QC/NJfreFOgDrZ9Fru+q43LCerqmc42A3l7iBfBBniFqQBpqNTXSpr28T55CE3ZJrqKrJ6fACiucW0ZverCNIbmbgMZ80QyeF3IVXAhcOzSbZU3nv3f2GDWfCs1eeTuv162D7Pal6t9w6bWuvDWJcPZfCL7WD/pU9n6ErQFQa+DrnvwbHl/pwIGuQPUURjiMASNE75zn3kmG48UHfyAUjcaHQg6uaDcKHg7RtocremgHr8AsgRvfRBUgNnu+xFPRPn7XrqyYJl+wGTIZD5glK7sxKuMRuaJDXHTRsmpnLcQ0qvP15zyRQZA2zY9lCT/Aof2dTYVkMiHlB/FABaD5qZKwNCNTThMGJbArd97XEuwwrVkmkxV3wfQAEOip4PzzI4v/R8+4RhFeej1+vqHKeC19itgDnrlfJE/Hgmuu0sHpGZB/P94vkAh9q/xxLwxMArOZGgBPKliapYDUb6OUzw7oGkoJrvHUvjY6ygpvRXQCj8uyhQ84tsab5CoFPPG7pXPuwdc6r5VswmPALlAIduOwut0IlG/AOOCKTicV7X9S0h19cyUalpgaLj+mjZzqtLRcYBao6l+ukwPLk4TQ2C2P6qZPOtR4=
